name: Deploy
on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-16.04
    steps:
      - name: Checkout project
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14.16.1'
      - name: Install dependencies
        run: yarn
      - name: Build App
        run: yarn build
      - name: Remove source
        run: rm -r src
      - name: Deploy to heroku
        uses: behe/heroku-build@v1
        with:
          app-name: "wrestling-like-bot"
          api-key: ${{ secrets.HEROKU_KEY }}
