name: Heroku Health
on:
  schedule:
    - cron: "*/10 * * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: wei/curl@v1
        with:
          args: -I https://wrestling-like-bot.herokuapp.com/
