name: Heroku Health
on:
  schedule:
    - cron: "*/30 * * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: mikeesto/heroku-awake@1.0.0
        with:
          URL: "https://wrestling-like-bot.herokuapp.com/"
